# Generated by Django 4.2.2 on 2023-06-19 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_ticket_seatnum_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.BooleanField(default=False, help_text='Specify if the booking is confirmed or pending', verbose_name='Confirmed'),
        ),
        migrations.RemoveField(
            model_name='play',
            name='genre',
        ),
        migrations.AddField(
            model_name='play',
            name='genre',
            field=models.ForeignKey(help_text='Choose play genre', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.genre'),
        ),
    ]
